### ISSUE TITLE
Pomalej klient

### ISSUE THREAD

**Issue by svetlym** [proarc/proarc-client#220]
Dobrý den,

novej klient je na našich ostrejch datech (desítky TB) řádově pomalejší než starej, na každou operaci čekáme až několik minut. V tomto stavu pro nás klient není produkčně použitelnej.

**Comment by albertoh** [comment]
Dobry den.

Potreboval bych vic informace: 
  - vsechny obrazovky jsou pomale? hledani? editaci?
  - jake mate casy odpovedi z API? muzete mi, prosim, poslat screenshot z debuggeru?
  - Muzu se nejak dostat k vasim datum abych mohl testovat?

**Comment by svetlym** [comment]
Dobrý den,

zkoušíme dál a informace budeme průběžně doplňovat. Aktuálně to vypadá, že klient je extrémně pomalej na počítači jedný kolegyně, ale ale u druhý běží celkem rychle. Zkoušely se křížem přihlásit pod svym účtem na druhym počítači a zdá se, že je to opravdu počítačem a nikoliv účtem v Proarcu. Na jednom z nich jsou Windows 7 (tam to běží pomalu), na druhym Windows 10. Zkoušim to ale z jiných W7 a načítá se mi to celkem rychle (několik vteřin, ne několik minut). Až je zjistíme, doplním verze prohlížeče.

> vsechny obrazovky jsou pomale? hledani? editaci?

Jestli to interpretuju správně, tak všechny. Kolegyně mě kdyžtak opraví.


> jake mate casy odpovedi z API? muzete mi, prosim, poslat screenshot z debuggeru?

Můžu poprosit o návod, jak se k příslušnýmu debuggeru dostanu? S Dev tools  v Chromu už jsem trochu pracoval, ale odezvy API jsem ještě nedebuggoval a nedaří se mi to tam najít.

> Muzu se nejak dostat k vasim datum abych mohl testovat?

Ano, obraťte se, prosím, na Lukáše Sýkoru. Založím pro vás na obou našich instalacích proarcu admin účet a pošlu Lukášovi přihlašovací údaje (na vás nemám mail).

Pokusíme se taky co nejdřív zprovoznit přístup ke klientovi z vnější sítě, aktuálně to jde  jen z vnitřní sítě Městské knihovny.

**Comment by svetlym** [comment]
Díval jsem se, co se děje v logu Tomcatu na Proarcu, když kolegyně pracuje v novym klientu z počítače, kde je klient pomalej, a hází to následující chyby:

```
Jun 29, 2022 3:17:36 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [Jersey Web Application] in context with path [/proarc] threw exception [com.sun.jersey.api.client.ClientHandlerException: java.io.IOException: Error writing to server] with root cause
java.io.IOException: Error writing to server
	at sun.net.www.protocol.http.HttpURLConnection.writeRequests(HttpURLConnection.java:700)
	at sun.net.www.protocol.http.HttpURLConnection.writeRequests(HttpURLConnection.java:712)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1588)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1495)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at com.sun.jersey.client.urlconnection.URLConnectionClientHandler._invoke(URLConnectionClientHandler.java:249)
	at com.sun.jersey.client.urlconnection.URLConnectionClientHandler.handle(URLConnectionClientHandler.java:149)
	at com.sun.jersey.api.client.filter.HTTPBasicAuthFilter.handle(HTTPBasicAuthFilter.java:104)
	at com.sun.jersey.api.client.Client.handle(Client.java:648)
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:680)
	at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
	at com.sun.jersey.api.client.WebResource$Builder.post(WebResource.java:568)
	at com.yourmediashelf.fedora.client.request.RiSearch.execute(RiSearch.java:221)
	at cz.cas.lib.proarc.common.fedora.SearchView.findAdvancedCountObjects(SearchView.java:626)
	at cz.cas.lib.proarc.common.fedora.SearchView.findAdvancedSearchCount(SearchView.java:458)
	at cz.cas.lib.proarc.webapp.server.rest.DigitalObjectResource.search(DigitalObjectResource.java:444)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at cz.cas.lib.proarc.authentication.ProarcAuthFilter.securedContent(ProarcAuthFilter.java:72)
	at cz.cas.lib.proarc.authentication.ProarcAuthFilter.doFilter(ProarcAuthFilter.java:50)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at cz.cas.lib.proarc.webapp.server.EditorServletConfiguration.doFilter(EditorServletConfiguration.java:96)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

Na disku je 16 TB volnýho místa.

**Comment by vlahoda** [comment]
Mohl byste na tom pomalem stroji zkusit vymazat cache browseru nebo na nem pouzit jiny browser, treba Firefox?

**Comment by svetlym** [comment]
Zkoušeli jsme včera upgrade Proarcu na aktuální verzi (klient i server), promazání cache prohlížeče a zároveň se automaticky updatoval Chrome. Něco z toho zřejmě pomohlo, kolegyni už to běží přiměřeně.

"Error writing to server" mi to ale do logu Tomcatu hází dál, poslední je z dnešního rána. Mám na to otevřít novou issue na githubu jádra?

**Comment by svetlym** [comment]
Klient už běží přiměřeně rychle, výjimkou je pouze přihlášení do Proarcu, to trvá i několik minut.

**Comment by svetlym** [comment]
@ZdenkaSera Jsem pro, není potřeba mít otevřené dvě issue na to samý. Zavírám.
