### ISSUE TITLE
Konfigurace klienta mimo build

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc-client#461]
Umožnit komfiguraci klienta mimo build aplikace (soubor globals.js by byl na úrovni složky html, která se nasazuje, při změně klienta).

příklad: složka /var/www/proarc.inovatika.dev bude obsahovat soubor globals.js, složku html a složku log.

**Comment by SykoraLukas** [comment]
Na API hotové, nutné volat pomocí následujících příkazů:

Přidány property, které říkají, jestli jsou sobory k dispozici.
```properties
### get aplikace info
GET {{proarcUrl}}/rest/v2/info
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
```

Získání jednotlivých souborů (vrací se obsah souboru)
``` properties
### get externe referencovane konfigu / lokalizacni soubory
GET {{proarcUrl}}/rest/v2/info/file?type=config
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

### get externe referencovane konfigu / lokalizacni soubory
GET {{proarcUrl}}/rest/v2/info/file?type=cs
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

### get externe referencovane konfigu / lokalizacni soubory
GET {{proarcUrl}}/rest/v2/info/file?type=en
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

### get externe referencovane konfigu / lokalizacni soubory
GET {{proarcUrl}}/rest/v2/info/file?type=csen
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
```


Ukázka chyby
```properties
### get externe referencovane konfigu / lokalizacni soubory
GET {{proarcUrl}}/rest/v2/info/file?type=fr
Accept: application/json
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
```

**Comment by albertoh** [comment]
Na klientu hotovo

**Comment by ZdenkaSera** [comment]
Konfigurace [tady](https://github.com/proarc/proarc/wiki/Konfigurace#nov%C3%BD-klient), další informace v propojeném issue [1656](https://github.com/proarc/proarc/issues/1656)

**Comment by PetrKotynek** [comment]
Nebyl by někde, prosím, k mání vzorový globals.js ? PK



ERROR SyntaxError: Unexpected token 'v', "var APP_GL"... is not valid JSON
    at JSON.parse (<anonymous>)
    at Object.next (main.8be952cec4f25136.js:1:985638)
    at S.next (main.8be952cec4f25136.js:1:3231390)
    at N._next (main.8be952cec4f25136.js:1:3231074)
    at N.next (main.8be952cec4f25136.js:1:3230769)
    at t.onFinalize (main.8be952cec4f25136.js:1:3235443)


![ui_err_1](https://github.com/user-attachments/assets/3725e1ba-4f2f-470d-b896-878de8d6a5ca)

**Comment by PetrKotynek** [comment]
Ano, pomohla věta: Pozor, konfigurační soubor musí být převeden do JSONu (bez komentářů).
Po reálné konverzi .js na .json poprvé naběhlo. 
PK

**Comment by PetrKotynek** [comment]
Zkouším na stroji s  Klient: Verze v2.3.2 (11.12.2024)Jádro: Verze 4.2.4 a s 4.2.3-Snapshot  a Klient: Verze v2.3.2 (02.10.2024) a moc to nefunguje. nevím, zdali sedí konverze do json formátu. viz conf.zip jakákoli aktivace sekce 4.2 to znehybní. PK

(4.2) Cesta k externe referencovanemu configu klienta
proarc.client.path.config=/var/www/proarc.{{organizace}}.cz/stable/assets/shared/globals.js
(4.2) Cesta k externe referencovanemu lokalizacnimu souboru cs klienta
proarc.client.path.languageCs=/var/www/proarc.{{organizace}}.cz/stable/assets/i18n/cs.json
(4.2) Cesta k externe referencovanemu lokalizacnimu souboru cs-en klient
proarc.client.path.languageCsEn=/var/www/proarc.{{organizace}}.cz/stable/assets/i18n/cs-en.json
(4.2) Cesta k externe referencovanemu lokalizacnimu souboru en klient
proarc.client.path.languageEn=/var/www/proarc.{{organizace}}.cz/stable/assets/i18n/en.json


[461_conf.zip](https://github.com/user-attachments/files/18299722/461_conf.zip)
[ozc-old.zip](https://github.com/user-attachments/files/18299723/ozc-old.zip)

**Comment by PetrKotynek** [comment]
poznatek 2 : když není  /shared/globals.js **neproběhne** proarclogin s důsledky . 
konf už může být nove
proarc.client.path.config= shared/neco.json  už nevadí.  Tedy ve /shared mám jak globals.js tak globals.json
PK

**Comment by SykoraLukas** [comment]
Pokud chcete toto používat, musí být zachován "defaultní" soubor globals.js ve složce /shared/ beze změn. Přepisu ho soubor, na který je odkázáno v proarc.cfg a parametru proarc.client.path.config. Tento soubor musí být ve formátu json. 

U nás to funguje tak, že ve složce .proarc (home proarcu) máme složky clientConfig, která má přímo pod sebou soubor globals.json. Na tento soubor odkazuje proarc.cfg s parametrem proarc.client.path.config=/data/.proarc/clientConfig/globals.json. Při nasazování nové verze klienta přepisujeme celou složku /var/www/proarc-master.inovatika.dev.

**Comment by PetrKotynek** [comment]
Napodobil jsem to
#proarc.client.path.config=/var/www/proarc-ozc-old.lib.cas.cz/assets/shared/ouput.json
proarc.client.path.config=/home/proarc/work_data/clientConfig/globals.json

a měním tam   navbarColor a  lang:  a k žádnému přepisování ve www... shared/ nedochází. Formálně asi OK 
PK

**Comment by PetrKotynek** [comment]
Zkoušeno na dalším stroji, nic.  Stále není úplně jasná ta konvertze .js to .json  třeba má ta zůstat 
var APP_GLOBAL =  {
}
?  
možná by pomohla vzorová dvojici globals.js globals.json z něčeho běžícího. PK
