### ISSUE TITLE
X-server - Chyba při načítání metadat z Alephu

### ISSUE THREAD

**Issue by fstepanovsky** [proarc/proarc-client#98]
Klient 1.0.3
ProArc 3.6.3

Pří pokusu o stažení metadat přes XServer se zobrazí načítací kolečko, které se nepřestane točit.
V javascriptové konzoli vykočí chyba:
```
ERROR TypeError: n.response.data is undefined
    editModsXml http://proarc.staff.mzk.cz/main.6c26ff3d8aa72346f826.js:1
    _next http://proarc.staff.mzk.cz/main.6c26ff3d8aa72346f826.js:1
    next http://proarc.staff.mzk.cz/main.6c26ff3d8aa72346f826.js:1
    _next http://proarc.staff.mzk.cz/main.6c26ff3d8aa72346f826.js:1
    next http://proarc.staff.mzk.cz/main.6c26ff3d8aa72346f826.js:1
    _next http://proarc.staff.mzk.cz/main.6c26ff3d8aa72346f826.js:1
    next http://proarc.staff.mzk.cz/main.6c26ff3d8aa72346f826.js:1
    notifyNext http://proarc.staff.mzk.cz/main.6c26ff3d8aa72346f826.js:1
    _next http://proarc.staff.mzk.cz/main.6c26ff3d8aa72346f826.js:1
    next http://proarc.staff.mzk.cz/main.6c26ff3d8aa72346f826.js:1
    s http://proarc.staff.mzk.cz/main.6c26ff3d8aa72346f826.js:1
    invokeTask http://proarc.staff.mzk.cz/polyfills.d795936709729848a152.js:1
    onInvokeTask http://proarc.staff.mzk.cz/main.6c26ff3d8aa72346f826.js:1
    invokeTask http://proarc.staff.mzk.cz/polyfills.d795936709729848a152.js:1
    runTask http://proarc.staff.mzk.cz/polyfills.d795936709729848a152.js:1
    invokeTask http://proarc.staff.mzk.cz/polyfills.d795936709729848a152.js:1
    _ http://proarc.staff.mzk.cz/polyfills.d795936709729848a152.js:1
    m http://proarc.staff.mzk.cz/polyfills.d795936709729848a152.js:1
main.6c26ff3d8aa72346f826.js:1:337776
```

Ve starém rozhraní ProArcu načtení metadat z katalogu funguje.

**Comment by fstepanovsky** [comment]
Přidávám stacktrace z ProArcu:
```
proarc_1  | Mar 31, 2021 5:25:33 PM cz.cas.lib.proarc.webapp.server.rest.DigitalObjectResource toError
proarc_1  | WARNING: Column:43 Line:55 XML document structures must start and end within the same entity.
proarc_1  | java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key Column:43 Line:55 XML document structures must start and end within the same entity.
proarc_1  |     at java.util.ResourceBundle.getObject(ResourceBundle.java:450)
proarc_1  |     at java.util.ResourceBundle.getObject(ResourceBundle.java:444)
proarc_1  |     at java.util.ResourceBundle.getString(ResourceBundle.java:407)
proarc_1  |     at cz.cas.lib.proarc.webapp.server.ServerMessages.getMessage(ServerMessages.java:40)
proarc_1  |     at cz.cas.lib.proarc.webapp.server.ServerMessages.getFormattedMessage(ServerMessages.java:44)
proarc_1  |     at cz.cas.lib.proarc.webapp.server.ServerMessages.getFormattedMessage(ServerMessages.java:58)
proarc_1  |     at cz.cas.lib.proarc.webapp.server.rest.DigitalObjectResource.toError(DigitalObjectResource.java:1129)
proarc_1  |     at cz.cas.lib.proarc.webapp.server.rest.DigitalObjectResource.updateDescriptionMetadata(DigitalObjectResource.java:1086)
proarc_1  |     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
proarc_1  |     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
proarc_1  |     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
proarc_1  |     at java.lang.reflect.Method.invoke(Method.java:498)
proarc_1  |     at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
proarc_1  |     at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
proarc_1  |     at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
proarc_1  |     at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
proarc_1  |     at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
proarc_1  |     at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
proarc_1  |     at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
proarc_1  |     at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
proarc_1  |     at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
proarc_1  |     at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
proarc_1  |     at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
proarc_1  |     at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
proarc_1  |     at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
proarc_1  |     at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
proarc_1  |     at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
proarc_1  |     at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
proarc_1  |     at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
proarc_1  |     at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
proarc_1  |     at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
proarc_1  |     at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
proarc_1  |     at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
proarc_1  |     at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
proarc_1  |     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
proarc_1  |     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
proarc_1  |     at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
proarc_1  |     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
proarc_1  |     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
proarc_1  |     at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:419)
proarc_1  |     at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:169)
proarc_1  |     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
proarc_1  |     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
proarc_1  |     at cz.cas.lib.proarc.authentication.ProarcAuthFilter.securedContent(ProarcAuthFilter.java:72)
proarc_1  |     at cz.cas.lib.proarc.authentication.ProarcAuthFilter.doFilter(ProarcAuthFilter.java:50)
proarc_1  |     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
proarc_1  |     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
proarc_1  |     at cz.cas.lib.proarc.webapp.server.EditorServletConfiguration.doFilter(EditorServletConfiguration.java:96)
proarc_1  |     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
proarc_1  |     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
proarc_1  |     at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
proarc_1  |     at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
proarc_1  |     at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
proarc_1  |     at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
proarc_1  |     at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
proarc_1  |     at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
proarc_1  |     at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
proarc_1  |     at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
proarc_1  |     at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:784)
proarc_1  |     at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
proarc_1  |     at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802)
proarc_1  |     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410)
proarc_1  |     at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
proarc_1  |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
proarc_1  |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
proarc_1  |     at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
proarc_1  |     at java.lang.Thread.run(Thread.java:748)
```

**Comment by ZdenkaSera** [comment]
@SykoraLukas @albertoh Prosím, není tohle z výše zmíněným verzím jádra/klienta k uzavření? Děkuji.

**Comment by SykoraLukas** [comment]
Uzavřeno na základě labelu během schůzky 17.6.2022.
